[package]
name = "profiled_config_macros"
version.workspace = true
edition = "2024"
description = "Procedural macros for profiled_config"
license = "MIT"
repository = "https://github.com/Athlaes/profiled-rust"
publish = ["crates-io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = {
    version = "2",
    features = ["full"]
}
