version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
